### ISSUE TITLE
maybe there is an error in theme.config 

### ISSUE THREAD

**Issue by yipanbo** [websemantics/semantic-dojo#10]
semantic dojo version:0.2.1
file:src->semantic-dojo-styles->src->theme.config
line:96
/\* Path to site override folder */
@siteFolder  : 'site';
may should be:@siteFolder  : '_site';

but,the file "theme.less" in the "semantic-dojo-0.2.1\src\semantic-dojo-styles\src\dijit" may error,
can you tell me a good way to resolve this problem?
thank you!

**Comment by websemantics** [comment]
Oh yes, the Semantic-UI documentation recommends that you rename `_site` to `site`, but with this project should set all that up for you, [see](https://github.com/websemantics/semantic-dojo-styles/tree/master/src/dijit/site) 
Sorry for the delay, and let me know if that didn't work,
