### ISSUE TITLE
integrate dgrid and dstore

### ISSUE THREAD

**Issue by juanjoc333** [websemantics/semantic-dojo#11]
Hi, Is there a way to integrate dgrid and dstore in the build process?

**Comment by websemantics** [comment]
Absolutely, 

Check how `dijit` components were setup here, 
https://github.com/websemantics/semantic-dojo-styles/tree/master/src

You would probably have to start by creating definitions for both at, 

`semantic-dojo-styles/src/dijit/definitions/modules/dgrid.less` &
`semantic-dojo-styles/src/dijit/definitions/modules/dstore.less`

Then for each you will need a variable and override configs in the default theme,

```
semantic-dojo-styles/src/dijit/themes/default/modules/dstore.overrides
semantic-dojo-styles/src/dijit/themes/default/modules/dstore.variables
semantic-dojo-styles/src/dijit/themes/default/modules/dgrid.overrides
semantic-dojo-styles/src/dijit/themes/default/modules/dgrid.variables
```

Then, add under modules to,
https://github.com/websemantics/semantic-dojo-styles/blob/master/src/semantic-dojo.less

And here,
https://github.com/websemantics/semantic-dojo-styles/blob/master/src/theme.config

Try to compile, if all went well, you have a successful integration of two new modules, .. apologies if I missed details, but let me know if you have any issues
