### ISSUE TITLE
how to change the font path?

### ISSUE THREAD

**Issue by Yuliang-Lee** [websemantics/semantic-dojo#6]
I want to change the font _Icons_ src "../dist/themes/default/assets/fonts/XXX" to another paths ranther than modefy it after buld.
what shall I do?

**Comment by websemantics** [comment]
You can do this from https://github.com/websemantics/semantic-dojo/blob/master/less/dijit/themes/default/elements/icon.variables, let me know if that didn't work

**Comment by Yuliang-Lee** [comment]
Thank you.It works.
