### ISSUE TITLE
the pageindex.html

### ISSUE THREAD

**Issue by yipanbo** [websemantics/semantic-dojo#9]
i think there is an error in href: 
`<link rel="icon" type="image/png" href="fsrc/app/resources/img/avicon-16x16.png" sizes="16x16" />`
should be:
`<link rel="icon" type="image/png" href="src/app/resources/img/favicon-16x16.png" sizes="16x16" />`

**Comment by websemantics** [comment]
Thanks @yipanbo, I found this in two files, fixed now.
